version: '3.9'
services:
  app:
    build: .
    container_name: golang_backend_template_dev
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
