// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/inference-jobs": {
            "get": {
                "description": "list all inference jobs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inference-jobs"
                ],
                "summary": "list all inference jobs",
                "operationId": "list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.listInferenceJobResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.eResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "create inference job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inference-jobs"
                ],
                "summary": "create inference job",
                "operationId": "create",
                "parameters": [
                    {
                        "description": "request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.createInferenceJobRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.createInferenceJobResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.eResponse"
                        }
                    }
                }
            }
        },
        "/inference-jobs/{id}": {
            "get": {
                "description": "get inference job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inference-jobs"
                ],
                "summary": "get inference job",
                "operationId": "get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.getInferenceJobResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.eResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete inference job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inference-jobs"
                ],
                "summary": "delete inference job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.sResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.eResponse"
                        }
                    }
                }
            }
        },
        "/training-jobs/all": {
            "get": {
                "description": "list all training jobs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "training-jobs"
                ],
                "summary": "list all training jobs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.getJobResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.eResponse"
                        }
                    }
                }
            }
        },
        "/training-jobs/create": {
            "post": {
                "description": "create training job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "training-jobs"
                ],
                "summary": "create training job",
                "parameters": [
                    {
                        "description": "request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.createTrainingJobRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.createTrainingJobResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.eResponse"
                        }
                    }
                }
            }
        },
        "/training-jobs/{id}": {
            "get": {
                "description": "get training job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "training-jobs"
                ],
                "summary": "get training job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.getJobResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.eResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.GenericJob": {
            "type": "object",
            "properties": {
                "jobId": {
                    "type": "string",
                    "example": "12345"
                },
                "jobName": {
                    "type": "string",
                    "example": "name"
                },
                "jobStatus": {
                    "type": "string",
                    "example": "jobStatus"
                }
            }
        },
        "v1.createInferenceJobRequest": {
            "type": "object"
        },
        "v1.createInferenceJobResponse": {
            "type": "object",
            "properties": {
                "entryPoint": {
                    "type": "string",
                    "example": "http://localhost:8080"
                },
                "jobId": {
                    "type": "string",
                    "example": "12345"
                }
            }
        },
        "v1.createTrainingJobRequest": {
            "type": "object",
            "properties": {
                "dockerImageName": {
                    "type": "string",
                    "example": "yjack0000cs12/llm-training:latest"
                },
                "twccJobId": {
                    "type": "string",
                    "example": "237139"
                }
            }
        },
        "v1.createTrainingJobResponse": {
            "type": "object",
            "properties": {
                "jobId": {
                    "type": "string",
                    "example": "12345"
                }
            }
        },
        "v1.eResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "message"
                }
            }
        },
        "v1.getInferenceJobResponse": {
            "type": "object",
            "properties": {
                "job": {
                    "$ref": "#/definitions/entity.GenericJob"
                }
            }
        },
        "v1.getJobResponse": {
            "type": "object",
            "properties": {
                "job": {
                    "$ref": "#/definitions/entity.GenericJob"
                }
            }
        },
        "v1.listInferenceJobResponse": {
            "type": "object",
            "properties": {
                "jobs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.GenericJob"
                    }
                }
            }
        },
        "v1.sResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "string",
                    "example": "message"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{"http", "https"},
	Title:            "swagger test",
	Description:      "swagger test example",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
